### ISSUE TITLE
引入不生效

### ISSUE THREAD

**Issue by jiaxin11** [laocaixw/SuspendButtonLayout#1]
Failed to resolve: com.laocaixw.suspendbuttonlayout:suspendbuttonlayout:1.0.0

**Comment by jiaxin11** [comment]
我想让他初始化的时候，放到布局的右边。该怎么做

**Comment by laocaixw** [comment]
1.引入不生效可能是网络访问超时了；
或者工程目录下build.gradle没有指定为jcenter：
allprojects {
    repositories {
        jcenter();
    }
}

2.初始化的时候，放到布局的右边。这个功能暂时没有，后面会扩展。

**Comment by laocaixw** [comment]
已增加按钮位置设置功能，用最新的版本 1.0.2 ：
dependencies { compile 'com.laocaixw.suspendbuttonlayout:suspendbuttonlayout:1.0.2' }
用法见README
