### ISSUE TITLE
主按钮展开时有个图标总在那里

### ISSUE THREAD

**Issue by fei-dawoo** [laocaixw/SuspendButtonLayout#2]
我现在主按钮是个半透明的图标，展开后会看到主按钮下还有一个类似消息的图标

**Comment by laocaixw** [comment]
主按钮有两种状态，打开时和关闭时的图标都需要设置，你是不是只设置了其中一个，而另一个用了默认的图标了？
suspend:imageMainClose="@mipmap/suspend_main_close"
suspend:imageMainOpen="@mipmap/suspend_main_open"

**Comment by fei-dawoo** [comment]
我都有设置，但是展开时始终有个默认图标

**Comment by laocaixw** [comment]
找到问题了，确实是个bug~在初始化几个图片控件的时候，默认初始化了6个。你现在着急用吗？不着急的话等我改了发布1.0.1版本，提交 jcenter 审核；着急的话，就直接复制依赖 Module 工程，将 SuspendButtonLayout 第 113 行 mResImage.length 改为 mNumber。

**Comment by laocaixw** [comment]
找到问题了，确实是个bug~在初始化几个图片控件的时候，默认初始化了6个。已经改好了，把依赖的版本改成 1.0.1
`
dependencies {
    compile 'com.laocaixw.suspendbuttonlayout:suspendbuttonlayout:1.0.1'
}
`

**Comment by fei-dawoo** [comment]
好的
