### ISSUE TITLE
怎么样能设置按钮开启时，单击空白处会自动关闭按钮

### ISSUE THREAD

**Issue by ykxdyy** [laocaixw/SuspendButtonLayout#7]
开启后 关闭按钮总是点不上

如果能在开启时，单击空白处就能关闭 就舒服多了

**Comment by laocaixw** [comment]
可以在空白处加点击事件，调关闭方法：suspendButtonLayout.closeSuspendButton();

**Comment by ykxdyy** [comment]
谢谢！
